[pytest]
addopts = -q -ra
testpaths =
    Testes
    Testes_Mobile
python_files = test_*.py
markers =
    smoke: testes rápidos
    regressao: testes lentos, garantem que modificações no código não prejudiquem as funcionalidades existentes.
    default: visão Default (other-regions)
    sul: visão Sul (southern-region)
    deslogado: teste usuário deslogado
    loginLogout: teste login e logout
    logado: teste usuário logado
    mobile: testes mobile
    primeiroAcesso: teste do primeiro acesso
    dashboard: teste do painel do usuário
    favoritos: teste da página lista de favoritos
    cart: teste do mini-cart e carrinho
    checkout: teste de finalização de compra
    redefinir_senha: teste da redefinação de senha
    lp: teste das paginas lps de marcas
    refazer: teste do refazer pedido
    mapa: teste do mapa de corte bovinos e cordeiro


